sudo: false

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

language: node_js
node_js:
- '8'
notifications:
  email: false
cache:
  directories:
    - "node_modules"
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
addons:
  apt:
    packages:
    - sshpass
before_install:
  - npm i -g npm@6.4.1
jobs:
  include:
    - stage: build 🔨
      install: npm ci
      script: npm run build
    - stage: quality ✔
      install: npm ci --ignore-scripts
      name: lint front
      script: npm run lint:js
    - name: lint back
      script: npm run lint:server
    - stage: deploy 📦
      install: npm ci --production
      name: online version
      deploy:
        # deploy develop to the staging environment
        - provider: script
          skip_cleanup: true
          script: bash build/deploy.sh $HOST_PREPROD $PATH_PREPROD $SSH_PASS_PREPROD
          on:
            repo: silexlabs/Silex
            branch: develop
        # deploy master to production
        - provider: script
          skip_cleanup: true
          script: bash build/deploy.sh $HOST_PROD $PATH_PROD $SSH_PASS_PROD
          on:
            repo: silexlabs/Silex
            branch: master
    - name: linux app
      install: npm ci
      if: branch = master AND repo = silexlabs/Silex
      script: npm run release
      os: linux
      dist: xenial
    - name: osx app
      if: branch = master AND repo = silexlabs/Silex
      script: npm run release
      os: osx

