contact_links:
  - name: Silex PRO
    url: http://eepurl.com/gjYnib
    about: To be listed as a professional selling Silex websites please join this group
  - name: Community chat
    url: https://gitter.im/silex-website-builder/community
    about: "Let's get in touch and talk about Silex" 
